// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit!  //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// i2c_tx  //
// ------- //

// PIO I2C transmit program — sends one byte per START-data-STOP frame.
//
// Pin mapping (open-drain: output values held at 0, direction controls drive):
//   SDA: OUT pindirs [0], SET pindirs [0], IN pins [0]
//   SCL: SIDESET pindirs [0] (1 bit, optional)
//
// TX FIFO word format:
//   Bits [31:24] = inverted data byte (MSB first, left-aligned for shift-left)
//   Software must write:  (uint32_t)(~data & 0xFF) << 24
//
// RX FIFO: 1-bit ACK/NAK status per byte (bit 0: 0=ACK, 1=NAK)
//
// Protocol per byte:
//   START → 8 data bits (MSB first) → read ACK → STOP → wrap

#define i2c_tx_wrap_target 0
#define i2c_tx_wrap 14

static const uint16_t i2c_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xf780, //  1: set    pindirs, 0       side 0 [7]  ; SDA=high, SCL=high
    0xf781, //  2: set    pindirs, 1       side 0 [7]  ; START: SDA->low, SCL=high
    0xbf42, //  3: nop                     side 1 [7]  ; SCL->low
    0xe027, //  4: set    x, 7                         ; 8-bit counter
    0x7f81, //  5: out    pindirs, 1       side 1 [7]  ; data bit on SDA, SCL=low
    0xb742, //  6: nop                     side 0 [7]  ; SCL->high (clock)
    0x1f45, //  7: jmp    x--, 5           side 1 [7]  ; SCL->low, loop
    0xff80, //  8: set    pindirs, 0       side 1 [7]  ; release SDA, SCL=low
    0xb742, //  9: nop                     side 0 [7]  ; SCL->high
    0x5301, // 10: in     pins, 1          side 0 [3]  ; sample ACK from SDA
    0x9800, // 11: push                    side 1      ; push ACK, SCL->low
    0xff81, // 12: set    pindirs, 1       side 1 [7]  ; SDA=low, SCL=low (STOP setup)
    0xb742, // 13: nop                     side 0 [7]  ; SCL->high
    0xf780, // 14: set    pindirs, 0       side 0 [7]  ; SDA->high (STOP)
            //     .wrap
};

#if !PICO_NO_HARDWARE

static const struct pio_program i2c_tx_program = {
    .instructions = i2c_tx_program_instructions,
    .length = 15,
    .origin = -1,
};

static inline pio_sm_config i2c_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2c_tx_wrap_target, offset + i2c_tx_wrap);
    sm_config_set_sideset(&c, 2, true, true);  // 1 bit + optional, pindirs
    return c;
}

// ---------------------------------------------------------------------------
// Helper functions (user code, not generated by pioasm)
// ---------------------------------------------------------------------------

// Initialize a PIO SM for I2C TX operation.
//
// sda_pin and scl_pin must be adjacent (scl_pin = sda_pin + 1).
// freq_hz sets the approximate SCL frequency (actual = sysclk / (clkdiv * 16)).
static inline void pio_i2c_init(PIO pio, uint sm, uint offset,
                                uint sda_pin, uint scl_pin, uint freq_hz) {
    pio_sm_config c = i2c_tx_program_get_default_config(offset);

    sm_config_set_out_pins(&c, sda_pin, 1);       // OUT -> SDA pindirs
    sm_config_set_set_pins(&c, sda_pin, 1);        // SET -> SDA pindirs
    sm_config_set_in_pins(&c, sda_pin);            // IN  <- SDA value
    sm_config_set_sideset_pins(&c, scl_pin);       // SIDESET -> SCL pindirs

    sm_config_set_out_shift(&c, false, false, 8);  // shift left, no autopull, 8 bits
    sm_config_set_in_shift(&c, false, false, 1);   // shift left, no autopush, 1 bit

    // SCL cycle ~ 16 SM cycles (8 low + 8 high with delay[7])
    float div = (float)clock_get_hz(clk_sys) / (float)(freq_hz * 16);
    sm_config_set_clkdiv(&c, div);

    pio_sm_init(pio, sm, offset, &c);

    // Set pin output values to 0 (open-drain: direction controls drive)
    pio_sm_set_pins_with_mask(pio, sm, 0, (1u << sda_pin) | (1u << scl_pin));

    // Release both pins (direction = 0 = input = float high via pull-up)
    pio_sm_set_pindirs_with_mask(pio, sm, 0, (1u << sda_pin) | (1u << scl_pin));
}

// Write an inverted byte to the TX FIFO (left-aligned for MSB-first shifting).
static inline void pio_i2c_put_byte(PIO pio, uint sm, uint8_t data) {
    pio_sm_put_blocking(pio, sm, (uint32_t)(~data & 0xFFu) << 24);
}

// Read and return the ACK/NAK bit from the RX FIFO.
// Returns true if ACK received (SDA=0), false if NAK (SDA=1).
static inline bool pio_i2c_check_ack(PIO pio, uint sm) {
    uint32_t ack_word = pio_sm_get_blocking(pio, sm);
    return (ack_word & 1u) == 0;
}

// Perform a complete I2C write transaction.
// Each byte is sent as an independent START-data-STOP frame (repeated START).
// Returns true if all bytes were ACK'd, false on first NAK.
//
// Note: This simple implementation uses one START-byte-STOP per byte.
// For multi-byte transactions without repeated START, a more complex
// PIO program with conditional START/STOP control would be needed.
static inline bool pio_i2c_write(PIO pio, uint sm, uint8_t addr,
                                 const uint8_t *data, uint32_t len) {
    // Send address byte (7-bit addr + write bit)
    pio_i2c_put_byte(pio, sm, (addr << 1) | 0u);
    if (!pio_i2c_check_ack(pio, sm)) return false;

    // Send data bytes
    for (uint32_t i = 0; i < len; i++) {
        pio_i2c_put_byte(pio, sm, data[i]);
        if (!pio_i2c_check_ack(pio, sm)) return false;
    }

    return true;
}

// Perform a complete I2C read transaction.
// Not yet implemented — requires a separate PIO program for read mode.
static inline bool pio_i2c_read(PIO pio, uint sm, uint8_t addr,
                                uint8_t *data, uint32_t len) {
    (void)pio; (void)sm; (void)addr; (void)data; (void)len;
    return false;
}

#endif // !PICO_NO_HARDWARE
