// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit!  //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// i2c_slave_rx   //
// -------------- //

// PIO I2C slave receiver — detects START, receives 8 data bits, generates ACK.
//
// Pin mapping (open-drain: output values 0, direction controls drive):
//   SDA: IN pins [0], SET pindirs [0]
//   SCL: JMP_PIN, SET pindirs [1] (via SET_BASE=SDA, SET_COUNT=2)
//
// RX FIFO: received byte in bits [31:24] (ISR left-shifted, 8 bits at a time)
//   CPU reads: (pio_sm_get(pio, sm) >> 24) & 0xFF
//
// After pushing each byte, the SM sends ACK then raises IRQ (relative flag 0)
// and stalls. The CPU must clear the IRQ flag to allow the SM to continue.
//
// Protocol per byte:
//   detect START → 8 data bits (MSB first) → push → ACK → IRQ wait → loop

#define i2c_slave_rx_wrap_target 0
#define i2c_slave_rx_wrap 17

static const uint16_t i2c_slave_rx_program_instructions[] = {
            //     .wrap_target
    0xe080, //  0: set    pindirs, 0            ; Release both SDA and SCL
    0x20a0, //  1: wait   1 pin, 0              ; Wait SDA high (relative to IN_BASE)
    0x2020, //  2: wait   0 pin, 0              ; Wait SDA falling edge
    0x00c5, //  3: jmp    pin, 5                ; SCL high? → START detected
    0x0000, //  4: jmp    0                      ; Else data transition, retry
    0xe027, //  5: set    x, 7                   ; 8-bit counter (read_byte entry)
    0x2001, //  6: wait   0 gpio, 1             ; bit_loop: wait SCL low
    0x2081, //  7: wait   1 gpio, 1             ; Wait SCL high
    0x4001, //  8: in     pins, 1               ; Sample SDA into ISR
    0x0046, //  9: jmp    x--, 6                ; Loop 8 times
    0x8000, // 10: push   noblock               ; Push received byte to RX FIFO
    0x2001, // 11: wait   0 gpio, 1             ; Wait SCL low (for ACK)
    0xe081, // 12: set    pindirs, 1            ; Drive SDA low (ACK)
    0x2081, // 13: wait   1 gpio, 1             ; Wait SCL high (master clocks ACK)
    0x2001, // 14: wait   0 gpio, 1             ; Wait SCL low (end ACK)
    0xe080, // 15: set    pindirs, 0            ; Release SDA
    0xc050, // 16: irq    wait 0 rel            ; Signal CPU, stall until cleared
    0x0005, // 17: jmp    5                      ; Continue receiving next byte
            //     .wrap
};

#if !PICO_NO_HARDWARE

static const struct pio_program i2c_slave_rx_program = {
    .instructions = i2c_slave_rx_program_instructions,
    .length = 18,
    .origin = 0,   // must load at offset 0 (absolute jump targets)
};

static inline pio_sm_config i2c_slave_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2c_slave_rx_wrap_target,
                           offset + i2c_slave_rx_wrap);
    return c;
}

// -------------- //
// i2c_slave_tx   //
// -------------- //

// PIO I2C slave transmitter — sends bytes from TX FIFO on master clock.
//
// Pin mapping (open-drain):
//   SDA: OUT pindirs [0], SET pindirs [0]
//   SCL: SET pindirs [1] (via SET_BASE=SDA, SET_COUNT=2)
//
// TX FIFO word format (same as i2c_tx master):
//   Bits [31:24] = inverted data byte (MSB first, left-aligned for shift-left)
//   Software must write:  (uint32_t)(~data & 0xFF) << 24
//
// RX FIFO: 1-bit ACK/NAK from master after each byte (bit 0: 0=ACK, 1=NAK)
//
// Protocol:
//   Wait for IRQ 4 (CPU signals "transmit mode")
//   PULL → 8 data bits → release SDA → read master ACK → IRQ wait → loop

#define i2c_slave_tx_wrap_target 0
#define i2c_slave_tx_wrap 13

static const uint16_t i2c_slave_tx_program_instructions[] = {
            //     .wrap_target
    0x20c4, // 18: wait   1 irq, 4              ; Wait for CPU to signal TX mode
    0x80a0, // 19: pull   block                 ; Get byte from TX FIFO
    0xe027, // 20: set    x, 7                   ; 8-bit counter
    0x2001, // 21: wait   0 gpio, 1             ; tx_loop: wait SCL low
    0x6081, // 22: out    pindirs, 1            ; Shift MSB to SDA OE
    0x2081, // 23: wait   1 gpio, 1             ; Wait SCL high
    0x0055, // 24: jmp    x--, 21               ; Loop 8 times
    0x2001, // 25: wait   0 gpio, 1             ; Wait SCL low
    0xe080, // 26: set    pindirs, 0            ; Release SDA
    0x2081, // 27: wait   1 gpio, 1             ; Wait SCL high
    0x4001, // 28: in     pins, 1               ; Sample master ACK/NAK
    0x8000, // 29: push   noblock               ; Push ACK to RX FIFO
    0xc050, // 30: irq    wait 0 rel            ; Signal CPU, stall
    0x0012, // 31: jmp    18                     ; Back to wait for next TX
            //     .wrap
};

static const struct pio_program i2c_slave_tx_program = {
    .instructions = i2c_slave_tx_program_instructions,
    .length = 14,
    .origin = 18,  // must load at offset 18 (absolute jump targets)
};

static inline pio_sm_config i2c_slave_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2c_slave_tx_wrap_target,
                           offset + i2c_slave_tx_wrap);
    return c;
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

// Initialize PIO SM for I2C slave receiver (SM0).
static inline void pio_i2c_slave_rx_init(PIO pio, uint sm, uint offset,
                                          uint sda_pin, uint scl_pin) {
    pio_sm_config c = i2c_slave_rx_program_get_default_config(offset);

    sm_config_set_in_pins(&c, sda_pin);            // IN  <- SDA value
    sm_config_set_set_pins(&c, sda_pin, 2);         // SET -> SDA+SCL pindirs
    sm_config_set_jmp_pin(&c, scl_pin);             // JMP PIN -> SCL

    sm_config_set_in_shift(&c, false, false, 8);    // shift left, no autopush, 8 bits

    // Slow clock: each PIO tick ~ 1 us at clkdiv=50 (50 MHz sys clock)
    // Must be fast enough to sample SCL edges reliably
    sm_config_set_clkdiv(&c, 1.0f);                // Run at full speed to track SCL

    pio_sm_init(pio, sm, offset, &c);

    // Set pin output values to 0 (open-drain)
    pio_sm_set_pins_with_mask(pio, sm, 0, (1u << sda_pin) | (1u << scl_pin));
    // Release both pins (input mode)
    pio_sm_set_pindirs_with_mask(pio, sm, 0, (1u << sda_pin) | (1u << scl_pin));
}

// Initialize PIO SM for I2C slave transmitter (SM1).
static inline void pio_i2c_slave_tx_init(PIO pio, uint sm, uint offset,
                                          uint sda_pin, uint scl_pin) {
    pio_sm_config c = i2c_slave_tx_program_get_default_config(offset);

    sm_config_set_out_pins(&c, sda_pin, 1);         // OUT -> SDA pindirs
    sm_config_set_set_pins(&c, sda_pin, 2);          // SET -> SDA+SCL pindirs
    sm_config_set_in_pins(&c, sda_pin);              // IN  <- SDA (for ACK read)

    sm_config_set_out_shift(&c, false, false, 8);    // shift left, no autopull, 8 bits
    sm_config_set_in_shift(&c, false, false, 1);     // shift left, no autopush, 1 bit

    sm_config_set_clkdiv(&c, 1.0f);                 // Full speed

    pio_sm_init(pio, sm, offset, &c);

    pio_sm_set_pins_with_mask(pio, sm, 0, (1u << sda_pin) | (1u << scl_pin));
    pio_sm_set_pindirs_with_mask(pio, sm, 0, (1u << sda_pin) | (1u << scl_pin));
}

// CPU-side handler: receive a write transaction from the I2C master.
// The PIO always ACKs every byte (no address filtering in PIO).
// The CPU reads the address byte + data bytes from the RX FIFO.
// Returns the 7-bit address received.
static inline uint8_t pio_i2c_slave_handle_write(PIO pio, uint sm_rx,
                                                   uint8_t *buf, uint32_t len) {
    // Read address byte (left-shifted in ISR)
    uint32_t raw = pio_sm_get_blocking(pio, sm_rx);
    uint8_t addr_byte = (raw >> 24) & 0xFF;
    pio->irq = (1u << sm_rx);  // W1C: clear SM's IRQ flag to release SM

    // Read data bytes
    for (uint32_t i = 0; i < len; i++) {
        raw = pio_sm_get_blocking(pio, sm_rx);
        buf[i] = (raw >> 24) & 0xFF;
        pio->irq = (1u << sm_rx);
    }

    return addr_byte >> 1;  // 7-bit address (strip R/W bit)
}

// CPU-side handler: service a read transaction from the I2C master.
// CPU loads data into SM1 TX FIFO, signals SM1 via IRQ 4.
static inline void pio_i2c_slave_handle_read(PIO pio, uint sm_rx, uint sm_tx,
                                               const uint8_t *buf, uint32_t len) {
    // SM0 already received the address byte — read and release
    uint32_t raw = pio_sm_get_blocking(pio, sm_rx);
    (void)raw;
    pio->irq = (1u << sm_rx);

    // Signal SM1 to start transmitting (set IRQ flag 4)
    pio->irq_force = (1u << 4);

    // Feed data bytes
    for (uint32_t i = 0; i < len; i++) {
        // Bit-invert for open-drain: pindirs=1 drives SDA low (I2C '0')
        pio_sm_put_blocking(pio, sm_tx, (uint32_t)(~buf[i] & 0xFFu) << 24);
        // Wait for SM1 to finish this byte (it sets its IRQ flag via irq wait 0 rel)
        while (!(pio->irq & (1u << sm_tx))) {}
        pio->irq = (1u << sm_tx);
    }
}

#endif // !PICO_NO_HARDWARE
