# Copyright OpenSoC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Pin constraints for AMD Kria KV260 Vision AI Starter Kit (XCK26-SFVC784-2LVI-C)
# Clock comes from the PS block (no external PL clock on KV260 carrier).
# All PL I/O are in bank 45 with VCCO = PL_3V3 (LVCMOS33).

# ==============================================================================
# Zynq UltraScale+ configuration
# NOTE: Clock constraint (create_clock) is generated by synth.tcl from
#       CLK_FREQ_MHZ — do not add it here.
# ==============================================================================
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]

# ==============================================================================
# LEDs (DS1-DS4) — bank 45, LVCMOS33
# ==============================================================================
set_property -dict { PACKAGE_PIN J11 IOSTANDARD LVCMOS33 } [get_ports {led[0]}]
set_property -dict { PACKAGE_PIN J10 IOSTANDARD LVCMOS33 } [get_ports {led[1]}]
set_property -dict { PACKAGE_PIN K13 IOSTANDARD LVCMOS33 } [get_ports {led[2]}]
set_property -dict { PACKAGE_PIN F11 IOSTANDARD LVCMOS33 } [get_ports {led[3]}]

# ==============================================================================
# Fan enable — bank 45, LVCMOS33
# ==============================================================================
set_property -dict { PACKAGE_PIN A12 IOSTANDARD LVCMOS33 } [get_ports fan_en_b]

# ==============================================================================
# UART via Pmod (pins 1 & 2) — bank 45, LVCMOS33
# ==============================================================================
set_property -dict { PACKAGE_PIN H12 IOSTANDARD LVCMOS33 } [get_ports uart_tx]
set_property -dict { PACKAGE_PIN B10 IOSTANDARD LVCMOS33 } [get_ports uart_rx]

# ==============================================================================
# I2C (HDA dedicated pins) — bank 45, LVCMOS33, open-drain SLOW slew
# ==============================================================================
set_property -dict { PACKAGE_PIN G11 IOSTANDARD LVCMOS33 SLEW SLOW } [get_ports i2c_scl]
set_property -dict { PACKAGE_PIN F10 IOSTANDARD LVCMOS33 SLEW SLOW } [get_ports i2c_sda]

# ==============================================================================
# GPIO via Pmod (pins 3–8) — bank 45, LVCMOS33
# ==============================================================================
set_property -dict { PACKAGE_PIN E10 IOSTANDARD LVCMOS33 } [get_ports {gpio[0]}]
set_property -dict { PACKAGE_PIN E12 IOSTANDARD LVCMOS33 } [get_ports {gpio[1]}]
set_property -dict { PACKAGE_PIN D10 IOSTANDARD LVCMOS33 } [get_ports {gpio[2]}]
set_property -dict { PACKAGE_PIN D11 IOSTANDARD LVCMOS33 } [get_ports {gpio[3]}]
set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [get_ports {gpio[4]}]
set_property -dict { PACKAGE_PIN B11 IOSTANDARD LVCMOS33 } [get_ports {gpio[5]}]

# ── Bitstream ─────────────────────────────────────────────────────────────────
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
