PROGRAM     = i2c_loopback_test
PROGRAM_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
INCS        += -I$(PROGRAM_DIR)/../../include -I$(PROGRAM_DIR)/../../lib
include $(PROGRAM_DIR)/../../common/common.mk
