# Copyright OpenSoC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

PROGRAM = uart_recv
PROGRAM_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

include $(PROGRAM_DIR)/../../../hw/ip/ibex/examples/sw/simple_system/common/common.mk
