PROGRAM = aes_test
PROGRAM_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

include $(PROGRAM_DIR)/../../../hw/ip/ibex/examples/sw/simple_system/common/common.mk
INCS += -I$(PROGRAM_DIR)/../../include
