PROGRAM     = conv2d_relu_softmax_stream_test
PROGRAM_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
INCS        += -I$(PROGRAM_DIR)/../../include
include $(PROGRAM_DIR)/../../common/common.mk
