#!/usr/bin/env python3
"""Generate one wrapper SV per (ADD, MUL, PIPE) combination."""
import argparse
import itertools
import pathlib
import sys

ADDS = {
    "operator":    "ADD_OPERATOR",
    "ripple":      "ADD_RIPPLE",
    "cla":         "ADD_CLA",
    "kogge_stone": "ADD_KOGGE_STONE",
    "brent_kung":  "ADD_BRENT_KUNG",
    "sklansky":    "ADD_SKLANSKY",
}
MULS = {
    "operator": "MUL_OPERATOR",
    "array":    "MUL_ARRAY",
    "booth4":   "MUL_BOOTH4",
    "wallace":  "MUL_WALLACE",
    "dadda":    "MUL_DADDA",
}
PIPES = [0, 1]

WRAPPER_TMPL = """\
// AUTOGENERATED by gen_wrappers.py — do not edit
module vec_mac_core_{add}_{mul}_p{pipe} (
  input  logic        clk_i,
  input  logic        rst_ni,
  input  logic        clear_i,
  input  logic        valid_i,
  input  logic [31:0] a_data_i,
  input  logic [31:0] b_data_i,
  output logic [31:0] result_o
);
  vec_mac_core #(
    .NUM_LANES       (4),
    .ADD_KIND        (arith_pkg::{add_enum}),
    .MUL_KIND        (arith_pkg::{mul_enum}),
    .MUL_PIPE_STAGES ({pipe}),
    .ADD_PIPE_STAGES ({pipe})
  ) u_dut (.*);
endmodule
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="Output directory")
    ap.add_argument("--adds", default=",".join(ADDS), help="Comma-separated adder names")
    ap.add_argument("--muls", default=",".join(MULS), help="Comma-separated mul names")
    ap.add_argument("--pipes", default="0,1", help="Comma-separated pipe depths")
    args = ap.parse_args()

    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    adds = args.adds.split(",")
    muls = args.muls.split(",")
    pipes = [int(p) for p in args.pipes.split(",")]

    for a, m, p in itertools.product(adds, muls, pipes):
        if a not in ADDS or m not in MULS or p not in PIPES:
            print(f"skip unknown ({a}, {m}, {p})", file=sys.stderr)
            continue
        name = f"{a}_{m}_p{p}"
        body = WRAPPER_TMPL.format(add=a, mul=m, pipe=p,
                                   add_enum=ADDS[a], mul_enum=MULS[m])
        (out / f"vec_mac_core_{name}.sv").write_text(body)
        print(name)

if __name__ == "__main__":
    main()
